# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/vivado/projects/pipelineCPU/pipelineCPU.srcs/sources_1/ip/ip_data_ram/ip_data_ram.xci
# IP: The module: 'ip_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado/projects/pipelineCPU/pipelineCPU.srcs/sources_1/ip/ip_data_ram/ip_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/vivado/projects/pipelineCPU/pipelineCPU.srcs/sources_1/ip/ip_data_ram/ip_data_ram.xci
# IP: The module: 'ip_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado/projects/pipelineCPU/pipelineCPU.srcs/sources_1/ip/ip_data_ram/ip_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
